#ifndef SPARK_HPP
#define SPARK_HPP

#include "api.hpp"
#include "app/application.hpp"
#include "ecs/component.hpp"
#include "ecs/entity.hpp"
#include "ecs/query.hpp"
#include "ecs/system.hpp"
#include "event/event.hpp"
#include "event/event_handler.hpp"
#include "pch.hpp"
#include "render/material.hpp"
#include "render/mesh.hpp"
#include "render/renderer.hpp"
#include "render/shader.hpp"
#include "render/vertex.hpp"
#include "resource/asset.hpp"
#include "system/file_serializer.hpp"
#include "system/manager.hpp"
#include "system/registry.hpp"
#include "system/serializer.hpp"
#include "util/defines.hpp"
#include "util/classic/file.hpp"
#include "profile/fps.hpp"
#include "util/general.hpp"
#include "util/thread_pool.hpp"
#include "util/container/variant.hpp"
#include "window/window.hpp"

#endif