#include "control.hpp"

namespace spark
{
	std::string to_string(Key key)
	{
		switch (key)
		{
			case Key::SPACE:
				return "SPACE";
			case Key::APOSTROPHE:
				return "APOSTROPHE";
			case Key::COMMA:
				return "COMMA";
			case Key::MINUS:
				return "MINUS";
			case Key::PERIOD:
				return "PERIOD";
			case Key::SLASH:
				return "SLASH";
			case Key::_0:
				return "0";
			case Key::_1:
				return "1";
			case Key::_2:
				return "2";
			case Key::_3:
				return "3";
			case Key::_4:
				return "4";
			case Key::_5:
				return "5";
			case Key::_6:
				return "6";
			case Key::_7:
				return "7";
			case Key::_8:
				return "8";
			case Key::_9:
				return "9";
			case Key::SEMICOLON:
				return "SEMICOLON";
			case Key::EQUAL:
				return "EQUAL";
			case Key::A:
				return "A";
			case Key::B:
				return "B";
			case Key::C:
				return "C";
			case Key::D:
				return "D";
			case Key::E:
				return "E";
			case Key::F:
				return "F";
			case Key::G:
				return "G";
			case Key::H:
				return "H";
			case Key::I:
				return "I";
			case Key::J:
				return "J";
			case Key::K:
				return "K";
			case Key::L:
				return "L";
			case Key::M:
				return "M";
			case Key::N:
				return "N";
			case Key::O:
				return "O";
			case Key::P:
				return "P";
			case Key::Q:
				return "Q";
			case Key::R:
				return "R";
			case Key::S:
				return "S";
			case Key::T:
				return "T";
			case Key::U:
				return "U";
			case Key::V:
				return "V";
			case Key::W:
				return "W";
			case Key::X:
				return "X";
			case Key::Y:
				return "Y";
			case Key::Z:
				return "Z";
			case Key::LEFT_BRACKET:
				return "LEFT_BRACKET";
			case Key::BACKSLASH:
				return "BACKSLASH";
			case Key::RIGHT_BRACKET:
				return "RIGHT_BRACKET";
			case Key::GRAVE_ACCENT:
				return "GRAVE_ACCENT";
			case Key::ESCAPE:
				return "ESCAPE";
			case Key::ENTER:
				return "ENTER";
			case Key::TAB:
				return "TAB";
			case Key::BACKSPACE:
				return "BACKSPACE";
			case Key::INSERT:
				return "INSERT";
			case Key::DELETE_KEY:
				return "DELETE";
			case Key::RIGHT:
				return "RIGHT";
			case Key::LEFT:
				return "LEFT";
			case Key::DOWN:
				return "DOWN";
			case Key::UP:
				return "UP";
			case Key::PAGE_UP:
				return "PAGE_UP";
			case Key::PAGE_DOWN:
				return "PAGE_DOWN";
			case Key::HOME:
				return "HOME";
			case Key::END:
				return "END";
			case Key::CAPS_LOCK:
				return "CAPS_LOCK";
			case Key::SCROLL_LOCK:
				return "SCROLL_LOCK";
			case Key::NUM_LOCK:
				return "NUM_LOCK";
			case Key::PRINT_SCREEN:
				return "PRINT_SCREEN";
			case Key::PAUSE:
				return "PAUSE";
			case Key::F1:
				return "F1";
			case Key::F2:
				return "F2";
			case Key::F3:
				return "F3";
			case Key::F4:
				return "F4";
			case Key::F5:
				return "F5";
			case Key::F6:
				return "F6";
			case Key::F7:
				return "F7";
			case Key::F8:
				return "F8";
			case Key::F9:
				return "F9";
			case Key::F10:
				return "F10";
			case Key::F11:
				return "F11";
			case Key::F12:
				return "F12";
			case Key::F13:
				return "F13";
			case Key::F14:
				return "F14";
			case Key::F15:
				return "F15";
			case Key::F16:
				return "F16";
			case Key::F17:
				return "F17";
			case Key::F18:
				return "F18";
			case Key::F19:
				return "F19";
			case Key::F20:
				return "F20";
			case Key::F21:
				return "F21";
			case Key::F22:
				return "F22";
			case Key::F23:
				return "F23";
			case Key::F24:
				return "F24";
			case Key::F25:
				return "F25";
			case Key::KP_0:
				return "KP_0";
			case Key::KP_1:
				return "KP_1";
			case Key::KP_2:
				return "KP_2";
			case Key::KP_3:
				return "KP_3";
			case Key::KP_4:
				return "KP_4";
			case Key::KP_5:
				return "KP_5";
			case Key::KP_6:
				return "KP_6";
			case Key::KP_7:
				return "KP_7";
			case Key::KP_8:
				return "KP_8";
			case Key::KP_9:
				return "KP_9";
			case Key::KP_DECIMAL:
				return "KP_DECIMAL";
			case Key::KP_DIVIDE:
				return "KP_DIVIDE";
			case Key::KP_MULTIPLY:
				return "KP_MULTIPLY";
			case Key::KP_SUBTRACT:
				return "KP_SUBTRACT";
			case Key::KP_ADD:
				return "KP_ADD";
			case Key::KP_ENTER:
				return "KP_ENTER";
			case Key::KP_EQUAL:
				return "KP_EQUAL";
			case Key::LEFT_SHIFT:
				return "LEFT_SHIFT";
			case Key::LEFT_CONTROL:
				return "LEFT_CONTROL";
			case Key::LEFT_ALT:
				return "LEFT_ALT";
			case Key::LEFT_SUPER:
				return "LEFT_SUPER";
			case Key::RIGHT_SHIFT:
				return "RIGHT_SHIFT";
			case Key::RIGHT_CONTROL:
				return "RIGHT_CONTROL";
			case Key::RIGHT_ALT:
				return "RIGHT_ALT";
			case Key::RIGHT_SUPER:
				return "RIGHT_SUPER";
			case Key::MENU:
				return "MENU";
			default:
				return "UNKNOWN KEY";
		}
	}

	std::string to_string(MouseButton button)
	{
		switch (button)
		{
			case MouseButton::LEFT_CLICK:
				return "LEFT_CLICK";
			case MouseButton::RIGHT_CLICK:
				return "RIGHT_CLICK";
			case MouseButton::MIDDLE_CLICK:
				return "MIDDLE_CLICK";
			case MouseButton::MOUSE_BUTTON_1:
				return "MOUSE_BUTTON_1";
			case MouseButton::MOUSE_BUTTON_2:
				return "MOUSE_BUTTON_2";
			case MouseButton::MOUSE_BUTTON_3:
				return "MOUSE_BUTTON_3";
			case MouseButton::MOUSE_BUTTON_4:
				return "MOUSE_BUTTON_4";
			case MouseButton::MOUSE_BUTTON_5:
				return "MOUSE_BUTTON_5";
			default:
				return "UNKNOWN MOUSE BUTTON";
		}
	}

	std::string to_string(ControllerButton button)
	{
		switch (button)
		{
			case ControllerButton::A:
				return "A";
			case ControllerButton::B:
				return "B";
			case ControllerButton::X:
				return "X";
			case ControllerButton::Y:
				return "Y";
			case ControllerButton::LEFT_BUMPER:
				return "LEFT_BUMPER";
			case ControllerButton::RIGHT_BUMPER:
				return "RIGHT_BUMPER";
			case ControllerButton::BACK:
				return "BACK";
			case ControllerButton::START:
				return "START";
			case ControllerButton::GUIDE:
				return "GUIDE";
			case ControllerButton::LEFT_THUMB:
				return "LEFT_THUMB";
			case ControllerButton::RIGHT_THUMB:
				return "RIGHT_THUMB";
			case ControllerButton::DPAD_UP:
				return "DPAD_UP";
			case ControllerButton::DPAD_RIGHT:
				return "DPAD_RIGHT";
			case ControllerButton::DPAD_DOWN:
				return "DPAD_DOWN";
			case ControllerButton::DPAD_LEFT:
				return "DPAD_LEFT";
				// No need for separate cases for CROSS, CIRCLE, SQUARE, and TRIANGLE as they are aliases
			default:
				return "UNKNOWN CONTROLLER BUTTON";
		}
	}

}