#ifndef SPARK_MACROS_HPP
#define SPARK_MACROS_HPP

#ifndef SPARK_EVENT_TYPES
#define SPARK_EVENT_TYPES

#define NO_EVENT 0
#define APP_UPDATE_EVENT 1
#define APP_TICK_EVENT 2
#define APP_RENDER_EVENT 3
#define WINDOW_CLOSED_EVENT 4
#define WINDOW_RESIZED_EVENT 5
#define WINDOW_MOVED_EVENT 6
#define KEY_PRESSED_EVENT 7
#define KEY_RELEASED_EVENT 8
#define KEY_REPEAT_EVENT 9
#define MOUSE_PRESSED_EVENT 10
#define MOUSE_RELEASED_EVENT 11
#define MOUSE_MOVE_EVENT 12
#define MOUSE_SCROLLED_EVENT 13
#define UDP_CLIENT_RECEIVE_EVENT 14
#define UDP_SERVER_RECEIVE_EVENT 15
#define TCP_CLIENT_RECEIVE_EVENT 16
#define TCP_SERVER_RECEIVE_EVENT 17
#define ENTITY_CREATED_EVENT 18
#define ENTITY_UPDATED_EVENT 19
#define ENTITY_DESTROYED_EVENT 20
#define API_CHANGED_EVENT 21

#endif

#ifndef SPARK_SUBSCRIPTION_TOPICS
#define SPARK_SUBSCRIPTION_TOPICS

#define NO_EVENT_TOPIC 0
#define EVERY_EVENT_TOPIC 1
#define WINDOW_EVENT_TOPIC 2
#define RENDERER_EVENT_TOPIC 3
#define APP_EVENT_TOPIC 4
#define INPUT_EVENT_TOPIC 5
#define UDP_CLIENT_RECEIVE_TOPIC 8
#define UDP_SERVER_RECEIVE_TOPIC 9
#define TCP_CLIENT_RECEIVE_TOPIC 10
#define TCP_SERVER_RECEIVE_TOPIC 11
#define CLIENT_RECEIVE_TOPIC TCP_CLIENT_RECEIVE_TOPIC | UDP_CLIENT_RECEIVE_TOPIC + 1000
#define SERVER_RECEIVE_TOPIC TCP_SERVER_RECEIVE_TOPIC | UDP_SERVER_RECEIVE_TOPIC + 1000
#define API_CHANGED_RECEIVE_TOPIC 12

#endif
#endif