#ifndef SPARK_MACROS_HPP
#define SPARK_MACROS_HPP

	#ifndef SPARK_EVENT_TYPES
	#define SPARK_EVENT_TYPES

		#define NO_EVENT 0
		#define APP_UPDATE_EVENT 1
		#define APP_TICK_EVENT 2
		#define APP_RENDER_EVENT 3
		#define WINDOW_CLOSED_EVENT 4
		#define WINDOW_RESIZED_EVENT 5
		#define WINDOW_MOVED_EVENT 6
		#define KEY_PRESSED_EVENT 7
		#define KEY_RELEASED_EVENT 8
		#define KEY_REPEAT_EVENT 9
		#define MOUSE_PRESSED_EVENT 10
		#define MOUSE_RELEASED_EVENT 11
		#define MOUSE_MOVE_EVENT 12
		#define MOUSE_SCROLLED_EVENT 13

	#endif

#ifndef SPARK_SUBSCRIPTION_TOPICS
#define SPARK_SUBSCRIPTION_TOPICS
        #define NO_EVENT_TOPIC 0
		#define EVERY_EVENT_TOPIC 1
		#define WINDOW_EVENT_TOPIC 2
		#define RENDERER_EVENT_TOPIC 3
		#define APP_EVENT_TOPIC 4
		#define INPUT_EVENT_TOPIC 5

     #endif
#endif