#ifndef SPARK_PCH_HPP
#define SPARK_PCH_HPP

#include <iostream>
#include <memory>
#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <set>
#include <map>
#include <thread>
#include <mutex>
#include <stack>
#include <queue>
#include <deque>
#include <shared_mutex>
#include <thread>
#include <list>
#include <functional>
#include <variant>
#include <tuple>
#include <bit>
#include <bitset>
#include <type_traits>
#include <typeinfo>
#include <typeindex>
#include <limits>
#include <cstdlib>
#include <initializer_list>
#include <numeric>
#include <optional>
#include <random>
#include <fstream>
#include <any>
#include <filesystem>
#include <future>
#include <chrono>
#include <stop_token>
#include <algorithm>
#include <ranges>
#include <cassert>
#include <array>
#include <regex>
#include <memory_resource>

#include "spark_defines.hpp"
#include "spark_types.hpp"
#include "spark_log.hpp"

#endif