#ifndef SPARK_EVENT_TYPE_HPP
#define SPARK_EVENT_TYPE_HPP

#include <core/pch.hpp>

namespace Spark
{
	enum class EventType
	{
		NONE = 0,
		WINDOW_CLOSE, WINDOW_RESIZE, WINDOW_FOCUS, WINDOW_LOST_FOCUS, WINDOW_MOVED,
		KEY_PRESSED, KEY_RELEASED, KEY_HELD,
		MOUSE_BUTTON_PRESSED, MOUSE_BUTTON_RELEASED, MOUSE_BUTTON_HELD, MOUSE_MOVED, MOUSE_SCROLLED
	};
}
#endif