#ifndef SPARK_EVENT_TYPE_HPP
#define SPARK_EVENT_TYPE_HPP

#include <core/pch.hpp>

namespace Spark
{

#define EVENT_TYPE_ALL -1
#define EVENT_TYPE_NONE 0

#define EVENT_TYPE_WINDOW_CLOSE 1
#define EVENT_TYPE_WINDOW_RESIZE 2
#define EVENT_TYPE_WINDOW_FOCUS 3
#define EVENT_TYPE_WINDOW_LOST_FOCUS 4
#define EVENT_TYPE_WINDOW_MOVED 5

#define EVENT_TYPE_KEY_PRESSED 6
#define EVENT_TYPE_KEY_RELEASED 7
#define EVENT_TYPE_KEY_HELD 8

#define EVENT_TYPE_MOUSE_BUTTON_PRESSED 9
#define EVENT_TYPE_MOUSE_BUTTON_RELEASED 10
#define EVENT_TYPE_MOUSE_BUTTON_HELD 11
#define EVENT_TYPE_MOUSE_MOVED 12
#define EVENT_TYPE_MOUSE_SCROLLED 13

#define EVENT_TYPE_ENTITY_CREATED 14
#define EVENT_TYPE_ENTITY_DESTROYED 15
#define EVENT_TYPE_COMPONENT_ADDED 16
#define EVENT_TYPE_COMPONENT_REMOVED 17

} // namespace Spark

#endif // SPARK_EVENT_TYPE_HPP
